# Generated by Django 4.2.4 on 2023-08-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=300)),
                ('slot', models.DateTimeField()),
                ('description', models.TimeField()),
            ],
        ),
    ]
