# Generated by Django 4.2.4 on 2023-08-24 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='slot',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 6, 35, 57, 142519, tzinfo=datetime.timezone.utc)),
        ),
    ]
